// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzJ2A0cbUwG419LiCLtGxX57BrJIVFos0',
    appId: '1:529329312613:web:4f439e861dceb41673078c',
    messagingSenderId: '529329312613',
    projectId: 'nepoofix',
    authDomain: 'nepoofix.firebaseapp.com',
    storageBucket: 'nepoofix.firebasestorage.app',
    measurementId: 'G-GDY5C4WESP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9pvGW9ugaDZYXBlu56V-zyISAB6OrTuQ',
    appId: '1:529329312613:android:48753c7174b9a75f73078c',
    messagingSenderId: '529329312613',
    projectId: 'nepoofix',
    storageBucket: 'nepoofix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzEfsAU1Zqy0kdDvpnJfXcx94fs5E2qAc',
    appId: '1:529329312613:ios:b87bdf57b368855673078c',
    messagingSenderId: '529329312613',
    projectId: 'nepoofix',
    storageBucket: 'nepoofix.firebasestorage.app',
    iosBundleId: 'com.example.nepooFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzEfsAU1Zqy0kdDvpnJfXcx94fs5E2qAc',
    appId: '1:529329312613:ios:b87bdf57b368855673078c',
    messagingSenderId: '529329312613',
    projectId: 'nepoofix',
    storageBucket: 'nepoofix.firebasestorage.app',
    iosBundleId: 'com.example.nepooFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzJ2A0cbUwG419LiCLtGxX57BrJIVFos0',
    appId: '1:529329312613:web:b9779d103635580073078c',
    messagingSenderId: '529329312613',
    projectId: 'nepoofix',
    authDomain: 'nepoofix.firebaseapp.com',
    storageBucket: 'nepoofix.firebasestorage.app',
    measurementId: 'G-KCPSPQR50S',
  );
}
